### ISSUE TITLE
Modify the FAQ & process on landing page

### ISSUE THREAD

**Issue by xyzerobtc** [zeroauthority-dao/Overview#49]
Sushil can you please modify the FAQ to look like https://blocksurvey.io/ FAQ? 

and add new image for the process

**Comment by SushilBro** [comment]
which image should I add for the process can you please elaborate on it.? @xyzerobtc

**Comment by SushilBro** [comment]
Actually, this is not the image i have designed all of these however I will redesign it @xyzerobtc.

**Comment by xyzerobtc** [comment]
@SushilBro can you get the image here? 
https://drive.google.com/file/d/1YgRUud8VOZH4MnoDe8douB5Deqseh_CD/view?usp=sharing

**Comment by SushilBro** [comment]
Brother i have already changed the font color and pushed the code yesterday so I believe no need to change it to the image.  @xyzerobtc

**Comment by xyzerobtc** [comment]
Thanks brother @SushilBro

**Comment by xyzerobtc** [comment]
Done.
