### ISSUE TITLE
View open profile url by wallet

### ISSUE THREAD

**Issue by xyzerobtc** [zeroauthority-dao/Overview#51]
About me: 
Find me on the Zero Authority Gig Marketplace.

**Comment by xyzerobtc** [comment]
![Image](https://github.com/zeroauthority-dao/Overview/assets/16929732/bccf8dd9-f2ab-4587-8a5e-97dd55e69b3d)

**Comment by xyzerobtc** [comment]
complete drop down for time zones

**Comment by xyzerobtc** [comment]
![profile account (1)](https://github.com/zeroauthority-dao/Overview/assets/16929732/9f362a60-1dad-48c4-92c9-77cb30e7d8ac)

**Comment by xyzerobtc** [comment]
@SushilBro to add STX address under the name

**Comment by SushilBro** [comment]
@xyzerobtc  please give me the text that I should add it on About field

**Comment by xyzerobtc** [comment]
update: 
https://www.loom.com/share/32f61bd747024154823e5bb86e45e072
