### ISSUE TITLE
Add road map to landing page

### ISSUE THREAD

**Issue by xyzerobtc** [zeroauthority-dao/Overview#53]
Road Map

**Comment by xyzerobtc** [comment]
add to the bottom of the page

**Comment by xyzerobtc** [comment]
![Image](https://github.com/zeroauthority-dao/Overview/assets/16929732/c8b98b30-2f5c-411f-9e4c-d496ebd9c31c)

**Comment by xyzerobtc** [comment]
please give this the heading "Gig Marketplace Road Map"

**Comment by SushilBro** [comment]
Is this an image we need to add or should I design it from scratch.? If it is an image then please share me this file. @xyzerobtc

**Comment by xyzerobtc** [comment]
@SushilBro please use the image here instead of designing in with HTML CSS. Can you click the image and when it opens new window save as JPEG?

**Comment by SushilBro** [comment]
Thanks @xyzerobtc

**Comment by xyzerobtc** [comment]
![Image](https://github.com/zeroauthority-dao/Overview/assets/16929732/a3a551ce-4868-4eea-92c0-00b19b36cdfe)

**Comment by xyzerobtc** [comment]
@HodlSTX @SushilBro can you please update new road map on testnet and mainnet?

**Comment by SushilBro** [comment]
So we need to delete the previous image and insert this image right.? @xyzerobtc

**Comment by xyzerobtc** [comment]
That’s correct @SushilBro 
Thanks brother 
Cc: @HodlSTX will push updates by tomorrow 
Thank you!

**Comment by SushilBro** [comment]
@xyzerobtc please make this image downloadable.

**Comment by xyzerobtc** [comment]
@SushilBro can you click on the photo then download it?

**Comment by SushilBro** [comment]
@xyzerobtc no brother it's not allowing me to download.

**Comment by xyzerobtc** [comment]
Sorry I’ll send to you on discord now.

**Comment by SushilBro** [comment]
Brother there is already a heading named Road Map in the image so should I delete the heading "Gig Marketplace Road Map" from the code or should we have both.? @xyzerobtc

**Comment by xyzerobtc** [comment]
That’s a good idea let me send new image @SushilBro

**Comment by xyzerobtc** [comment]
![Image](https://github.com/zeroauthority-dao/Overview/assets/16929732/58e782fc-266a-43e6-b9bc-92eae4aab18f)

**Comment by xyzerobtc** [comment]
Updated.
